services:
  postgres:
    image: 'postgres:14-alpine'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=trashcan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
  trashcan:
    build: .
    command: java -jar /trashcan/trashcan.war
    volumes:
      - .:/source
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
